spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: 127.0.0.1
      password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sout?? ???? ??
        format_sql: true

  application:
    name: spring-boot-admin-test
#    security:
#      user:
#        name: "admin"
#        password: "admin"

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secret: studyjwtstudyjwtstudyjwt
  access-token-expiration-sec: 1800
  refresh-token-expiration-sec: 1209600

